name: Auto Update JioTV hdnea Cookie (Every 4 Hours)
permissions:
  contents: write
on:
  schedule:
    - cron: '0 */4 * * *' # Every 4 hours (0:00, 4:00, 8:00, 12:00, 16:00, 20:00 UTC)
  workflow_dispatch: # Manual trigger
jobs:
  update-cookies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to avoid shallow clone issues
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Fetch JSON and Extract hdnea Cookie
        run: |
          echo "=== Fetching JSON from https://jo-json.vodep39240327.workers.dev/ ==="
          curl -s -f https://jo-json.vodep39240327.workers.dev/ > stream.json || {
            echo "✗ ERROR: Failed to fetch JSON."
            exit 1
          }
          if [ ! -s stream.json ]; then
            echo "✗ ERROR: JSON file is empty."
            exit 1
          fi
          echo "✓ JSON fetched. File size: $(wc -c < stream.json) bytes"

          echo "=== Extracting __hdnea__ Cookie ==="
          FULL_URL=$(jq -r '.url' stream.json 2>/dev/null || echo "null")
          if [ "$FULL_URL" = "null" ] || [ -z "$FULL_URL" ]; then
            echo "✗ ERROR: No valid URL found in JSON. Update skipped."
            rm -f stream.json
            exit 0
          fi

          NEW_COOKIE=$(echo "$FULL_URL" | grep -o '__hdnea__=[^&]*' || echo "null")
          if [ "$NEW_COOKIE" = "null" ] || [ -z "$NEW_COOKIE" ]; then
            echo "✗ ERROR: No valid __hdnea__ cookie found. Update skipped."
            rm -f stream.json
            exit 0
          fi
          echo "✓ __hdnea__ Cookie: $NEW_COOKIE"
      - name: Update Jiotv.json
        run: |
          echo "=== Updating Jiotv.json ==="
          cp Jiotv.json Jiotv_backup.json 2>/dev/null || echo '[{"cookie": ""}]' > Jiotv_backup.json
          if ! jq -e . Jiotv_backup.json >/dev/null 2>&1; then
            echo "✗ WARNING: Jiotv.json is invalid JSON. Initializing new structure."
            echo '[{"cookie": "'"$NEW_COOKIE"'"}]' > Jiotv_backup.json
          fi
          jq --arg new_cookie "$NEW_COOKIE" 'map(if .cookie then .cookie = $new_cookie else . + {"cookie": $new_cookie} end)' Jiotv_backup.json > Jiotv_updated.json
          mv Jiotv_updated.json Jiotv.json
          echo "✓ Jiotv.json updated with cookie: $NEW_COOKIE"

          git add Jiotv.json
      - name: Clean Up
        run: |
          rm -f stream.json Jiotv_backup.json
          echo "✓ Cleaned up temporary files"
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          if git diff --staged --quiet; then
            echo "✓ No changes to Jiotv.json. Skipping commit."
            exit 0
          fi

          git commit -m "Update __hdnea__ cookie in Jiotv.json (${{ github.sha }})"
          git pull --rebase origin main || {
            echo "✗ ERROR: Git pull --rebase failed."
            git status
            exit 1
          }
          git push || {
            echo "✗ ERROR: Git push failed. Check GITHUB_TOKEN or permissions."
            git status
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
