name: Auto Update JioTV hdnea Cookie for All Channels (Every 6 Hours)
permissions:
  contents: write
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours (0:00, 6:00, 12:00, 18:00 UTC)
  workflow_dispatch: # Manual trigger
jobs:
  update-cookies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to avoid shallow clone issues
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Fetch JSON and Extract hdnea Cookie
        run: |
          echo "=== Fetching JSON from https://jo-json.vodep39240327.workers.dev/ ==="
          curl -s -f --retry 3 --retry-delay 5 https://jo-json.vodep39240327.workers.dev/ > stream.json || {
            echo "✗ ERROR: Failed to fetch JSON after retries."
            exit 1
          }
          if [ ! -s stream.json ]; then
            echo "✗ ERROR: JSON file is empty."
            exit 1
          fi
          echo "✓ JSON fetched. File size: $(wc -c < stream.json) bytes"

          echo "=== JSON Content ==="
          cat stream.json | jq . || {
            echo "✗ ERROR: JSON is invalid. Dumping raw content:"
            cat stream.json
            exit 1
          }

          echo "=== Extracting __hdnea__ Cookie ==="
          # Try cookie field in flat or nested structure
          NEW_COOKIE=$(jq -r '
            .cookie // 
            (.channels[]? | .cookie) // 
            "" | select(. != "" and test("^__hdnea__=")) | first' stream.json 2>/dev/null || echo "null")
          if [ "$NEW_COOKIE" = "null" ] || [ -z "$NEW_COOKIE" ]; then
            echo "✗ ERROR: No valid __hdnea__ cookie found. Tried fields: cookie, channels[].cookie. Dumping JSON:"
            cat stream.json | jq .
            rm -f stream.json
            exit 0
          fi
          echo "✓ __hdnea__ Cookie: $NEW_COOKIE"
      - name: Update Jiotv.json for All Channels
        run: |
          echo "=== Updating Jiotv.json ==="
          # Ensure Jiotv.json exists
          cp Jiotv.json Jiotv_backup.json 2>/dev/null || echo '[{"channel": "Unknown", "cookie": ""}]' > Jiotv_backup.json
          if ! jq -e . Jiotv_backup.json >/dev/null 2>&1; then
            echo "✗ WARNING: Jiotv.json is invalid JSON. Initializing new structure."
            echo '[{"channel": "Unknown", "cookie": "'"$NEW_COOKIE"'"}]' > Jiotv_backup.json
          fi
          # Update cookie for all channels
          jq --arg new_cookie "$NEW_COOKIE" '[.[] | .cookie = $new_cookie]' Jiotv_backup.json > Jiotv_updated.json
          mv Jiotv_updated.json Jiotv.json
          echo "✓ Jiotv.json updated with cookie for all channels: $NEW_COOKIE"
          echo "=== Jiotv.json Content ==="
          cat Jiotv.json | jq .

          git add Jiotv.json
      - name: Clean Up
        run: |
          rm -f stream.json Jiotv_backup.json
          echo "✓ Cleaned up temporary files"
      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Commit even if changes are minor
          git commit -m "Update __hdnea__ cookie for all channels in Jiotv.json (${{ github.sha }})" || {
            echo "✓ No changes to Jiotv.json. Committing to verify update."
            git commit -m "No-op commit to verify Jiotv.json update (${{ github.sha }})" --allow-empty
          }

          git pull --rebase origin main || {
            echo "✗ ERROR: Git pull --rebase failed."
            git status
            exit 1
          }
          git push || {
            echo "✗ ERROR: Git push failed. Check GITHUB_TOKEN or permissions."
            git status
            exit 1
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
